/**
 * Traduce exercises-data.json al español SIN llamar APIs externas.
 * - Tipos (level, mechanic, category, equipment, muscles, bodyParts): diccionarios
 * - Nombres: tabla de lookup NAME_ES (542 ejercicios)
 * - Instrucciones: traductor regex por frases y palabras
 */
import { readFileSync, writeFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const JSON_PATH = path.join(__dirname, "exercises-data.json");

// ── Diccionarios de tipos ──────────────────────────────────────────────────────

const LEVEL_ES = {
  beginner: "principiante",
  intermediate: "intermedio",
  advanced: "avanzado",
  expert: "experto",
};

const MECHANIC_ES = {
  compound: "compuesto",
  isolation: "aislamiento",
};

const CATEGORY_ES = {
  strength: "fuerza",
  stretching: "estiramiento",
  cardio: "cardio",
  plyometrics: "pliometría",
  powerlifting: "powerlifting",
  "olympic weightlifting": "levantamiento olímpico",
  strongman: "strongman",
};

const EQUIPMENT_ES = {
  barbell: "barra",
  dumbbell: "mancuerna",
  "body only": "peso corporal",
  "body weight": "peso corporal",
  cable: "cable",
  machine: "máquina",
  "leverage machine": "máquina de palanca",
  "smith machine": "máquina Smith",
  kettlebells: "pesa rusa",
  kettlebell: "pesa rusa",
  "ez barbell": "barra EZ",
  "resistance band": "banda de resistencia",
  bands: "bandas",
  band: "banda",
  assisted: "asistido",
  weighted: "con peso adicional",
  "exercise ball": "pelota de ejercicio",
  "medicine ball": "balón medicinal",
  "foam roll": "rodillo de espuma",
  "sled machine": "máquina de trineo",
  other: "otro",
};

const BODY_PART_ES = {
  "upper legs": "piernas (cuádriceps/isquios)",
  "lower legs": "piernas (gemelos/tibial)",
  "upper arms": "brazos (bíceps/tríceps)",
  "lower arms": "antebrazos",
  chest: "pecho",
  back: "espalda",
  shoulders: "hombros",
  waist: "abdomen/cintura",
  neck: "cuello",
  cardio: "cardio",
  other: "otro",
};

const MUSCLE_ES = {
  abdominals: "abdominales",
  abs: "abdominales",
  obliques: "oblicuos",
  hamstrings: "isquiotibiales",
  calves: "pantorrillas",
  biceps: "bíceps",
  triceps: "tríceps",
  glutes: "glúteos",
  quadriceps: "cuádriceps",
  chest: "pecho",
  pectorals: "pectorales",
  lats: "dorsales",
  back: "espalda",
  "middle back": "espalda media",
  "lower back": "espalda baja",
  "upper back": "espalda alta",
  traps: "trapecios",
  trapezius: "trapecio",
  forearms: "antebrazos",
  shoulders: "hombros",
  neck: "cuello",
  "hip flexors": "flexores de cadera",
  adductors: "aductores",
  abductors: "abductores",
  brachialis: "braquial anterior",
  "spinal erectors": "erectores de la columna",
  rhomboids: "romboides",
  "serratus anterior": "serrato anterior",
  "rear deltoids": "deltoides posteriores",
  deltoids: "deltoides",
  delts: "deltoides",
  spine: "columna vertebral",
};

// ── Tabla de nombres ───────────────────────────────────────────────────────────

const NAME_ES = {
  // strength
  "hack calf raise": "Elevación de talones en hack",
  "sled 45° leg press (side pov)": "Press de piernas en trineo 45°",
  "dumbbell front raise": "Elevación frontal con mancuerna",
  "dumbbell over bench revers wrist curl": "Curl de muñeca inverso con mancuerna",
  "barbell incline bench press": "Press inclinado con barra",
  "cable squatting curl": "Curl en cuclillas con cable",
  "dumbbell one arm hammer preacher curl": "Curl martillo en predicador un brazo",
  "barbell standing close grip curl": "Curl de pie agarre cerrado con barra",
  "kettlebell pistol squat": "Sentadilla pistola con pesa rusa",
  "impossible dips": "Fondos imposibles",
  "barbell seated overhead triceps extension": "Extensión de tríceps sobre cabeza sentado con barra",
  "smith incline bench press": "Press inclinado en máquina Smith",
  "weighted side bend (on stability ball)": "Flexión lateral con peso en pelota",
  "dumbbell one arm upright row": "Remo vertical un brazo con mancuerna",
  "barbell standing rocking leg calf raise": "Elevación de pantorrilla oscilante con barra",
  "barbell wrist curl v. 2": "Curl de muñeca con barra v.2",
  "dumbbell lying single extension": "Extensión individual acostado con mancuerna",
  "dumbbell reverse spider curl": "Curl araña inverso con mancuernas",
  "bent knee lying twist (male)": "Giro acostado con rodillas flexionadas",
  "lever front pulldown": "Jalón frontal en palanca",
  "lever seated row": "Remo sentado en palanca",
  "dumbbell standing concentration curl": "Curl de concentración de pie con mancuerna",
  "cable decline fly": "Apertura declinada con cable",
  "smith leg press": "Press de piernas en máquina Smith",
  "dumbbell palms in incline bench press": "Press inclinado agarre neutro con mancuernas",
  "cable seated curl": "Curl sentado con cable",
  "barbell standing calf raise": "Elevación de pantorrilla de pie con barra",
  "weighted hyperextension (on stability ball)": "Hiperextensión con peso en pelota",
  "cable seated crunch": "Crunch sentado con cable",
  "barbell bench press - medium grip": "Press de banca con barra - Agarre medio",
  "barbell deadlift": "Peso muerto con barra",
  "barbell full squat": "Sentadilla completa con barra",
  "barbell hack squat": "Hack squat con barra",
  "barbell incline bench press - medium grip": "Press inclinado con barra - Agarre medio",
  "barbell lunge": "Zancada con barra",
  "barbell shoulder press": "Press de hombros con barra",
  "barbell squat": "Sentadilla con barra",
  "barbell walking lunge": "Zancada caminando con barra",
  "bench dips": "Fondos en banco",
  "bent over barbell row": "Remo inclinado con barra",
  "bodyweight squat": "Sentadilla con peso corporal",
  "chin-up": "Dominada supina",
  "close-grip barbell bench press": "Press de banca agarre cerrado con barra",
  "decline barbell bench press": "Press declinado con barra",
  "decline dumbbell bench press": "Press declinado con mancuernas",
  "dumbbell bench press": "Press de banca con mancuernas",
  "dumbbell bench press with neutral grip": "Press de banca agarre neutro con mancuernas",
  "dumbbell lunges": "Zancadas con mancuernas",
  "dumbbell one-arm shoulder press": "Press de hombros un brazo con mancuerna",
  "dumbbell rear lunge": "Zancada trasera con mancuernas",
  "dumbbell shoulder press": "Press de hombros con mancuernas",
  "dumbbell squat": "Sentadilla con mancuernas",
  "elevated back lunge": "Zancada trasera elevada",
  "freehand jump squat": "Sentadilla con salto sin peso",
  "front barbell squat": "Sentadilla frontal con barra",
  "front squat (clean grip)": "Sentadilla frontal (agarre limpio)",
  "hammer grip incline db bench press": "Press inclinado agarre martillo con mancuernas",
  "handstand push-ups": "Flexiones en parada de manos",
  "incline push-up": "Flexión inclinada",
  "narrow stance squats": "Sentadilla con piernas juntas",
  "one arm dumbbell bench press": "Press de banca un brazo con mancuerna",
  "one leg barbell squat": "Sentadilla una pierna con barra",
  "plie dumbbell squat": "Sentadilla plie con mancuerna",
  "push-up wide": "Flexión agarre ancho",
  "push-ups - close triceps position": "Flexiones posición cerrada para tríceps",
  "push-ups with feet elevated": "Flexiones con pies elevados",
  "pushups": "Flexiones",
  "romanian deadlift": "Peso muerto rumano",
  "seated barbell military press": "Press militar sentado con barra",
  "single-arm push-up": "Flexión un brazo",
  "speed squats": "Sentadillas explosivas",
  "split squat with dumbbells": "Sentadilla dividida con mancuernas",
  "squat jerk": "Sentadilla-jerk",
  "squat with plate movers": "Sentadilla con discos",
  "standing military press": "Press militar de pie",
  "stiff-legged barbell deadlift": "Peso muerto piernas rígidas con barra",
  "stiff-legged dumbbell deadlift": "Peso muerto piernas rígidas con mancuernas",
  "upright barbell row": "Remo vertical con barra",
  "weighted jump squat": "Sentadilla con salto y peso",
  "weighted sissy squat": "Sentadilla sissy con peso",
  "wide-grip barbell bench press": "Press de banca agarre ancho con barra",
  "wide-grip decline barbell bench press": "Press declinado agarre ancho con barra",
  "wide-grip rear pull-up": "Dominada trasera agarre ancho",
  "wide stance barbell squat": "Sentadilla sumo con barra",
  "zercher squats": "Sentadilla Zercher",
  "alternating cable shoulder press": "Press de hombros alternado con cable",
  "cable deadlifts": "Peso muerto con cable",
  "cable shoulder press": "Press de hombros con cable",
  "close-grip front lat pulldown": "Jalón al pecho agarre cerrado",
  "face pull": "Face pull con cable",
  "full range-of-motion lat pulldown": "Jalón al pecho rango completo",
  "one arm lat pulldown": "Jalón un brazo con cable",
  "seated cable shoulder press": "Press de hombros sentado con cable",
  "wide-grip lat pulldown": "Jalón al pecho agarre ancho",
  "goblet squat": "Sentadilla goblet",
  "hack squat": "Hack squat",
  "kettlebell one-legged deadlift": "Peso muerto una pierna con pesa rusa",
  "kettlebell pistol squat": "Sentadilla pistola con pesa rusa",
  "kettlebell turkish get-up (lunge style)": "Turkish Get-Up con pesa rusa (estilo zancada)",
  "kettlebell turkish get-up (squat style)": "Turkish Get-Up con pesa rusa (estilo sentadilla)",
  "leg press": "Press de piernas",
  "leverage deadlift": "Peso muerto en máquina de palanca",
  "leverage shoulder press": "Press de hombros en máquina de palanca",
  "lying cambered barbell row": "Remo con barra curvada acostado",
  "lying machine squat": "Sentadilla en máquina acostado",
  "machine bench press": "Press de pecho en máquina",
  "narrow stance hack squats": "Hack squat piernas juntas",
  "narrow stance leg press": "Press de piernas piernas juntas",
  "plyo kettlebell pushups": "Flexiones pliométricas con pesa rusa",
  "smith machine bench press": "Press de banca en máquina Smith",
  "smith machine bent over row": "Remo inclinado en máquina Smith",
  "smith machine close-grip bench press": "Press de banca agarre cerrado en máquina Smith",
  "smith machine decline press": "Press declinado en máquina Smith",
  "smith machine incline bench press": "Press inclinado en máquina Smith",
  "smith machine leg press": "Press de piernas en máquina Smith",
  "smith machine overhead shoulder press": "Press militar en máquina Smith",
  "smith machine pistol squat": "Sentadilla pistola en máquina Smith",
  "smith machine squat": "Sentadilla en máquina Smith",
  "smith machine stiff-legged deadlift": "Peso muerto piernas rígidas en máquina Smith",
  "smith single-leg split squat": "Sentadilla dividida una pierna en máquina Smith",
  "two-arm kettlebell military press": "Press militar dos brazos con pesas rusas",
  "barbell incline shoulder raise": "Elevación de hombros inclinada con barra",
  "bent-arm barbell pullover": "Pullover con barra brazos flexionados",
  "bent-arm dumbbell pullover": "Pullover con mancuerna brazos flexionados",
  "bent-knee hip raise": "Elevación de cadera con rodillas flexionadas",
  "cross-body crunch": "Crunch cruzado",
  "decline close-grip bench to skull crusher": "Press declinado agarre cerrado a rompecráneos",
  "decline dumbbell flyes": "Apertura declinada con mancuernas",
  "decline oblique crunch": "Crunch oblicuo declinado",
  "decline reverse crunch": "Crunch inverso declinado",
  "dumbbell raise": "Elevación con mancuerna",
  "incline dumbbell flyes": "Apertura inclinada con mancuernas",
  "push up to side plank": "Flexión a plancha lateral",
  "step-up with knee raise": "Subida al cajón con elevación de rodilla",
  "stiff leg barbell good morning": "Buenos días piernas rígidas con barra",
  "straight-arm dumbbell pullover": "Pullover con mancuerna brazos extendidos",
  "wide-grip decline barbell pullover": "Pullover declinado agarre ancho con barra",
  "calf press on the leg press machine": "Press de pantorrilla en máquina de piernas",
  "elevated cable rows": "Remo alto con cable",
  "high cable curls": "Curl alto con cable",
  "seated cable rows": "Remo sentado con cable",
  "upright cable row": "Remo vertical con cable",
  "alternate hammer curl": "Curl martillo alterno",
  "alternate incline dumbbell curl": "Curl inclinado alterno con mancuernas",
  "alternating deltoid raise": "Elevación de deltoides alterna",
  "band assisted pull-up": "Dominada asistida con banda",
  "barbell curl": "Curl con barra",
  "barbell curls lying against an incline": "Curl con barra apoyado en banco inclinado",
  "barbell seated calf raise": "Elevación de pantorrilla sentado con barra",
  "barbell shrug": "Encogimientos con barra",
  "barbell shrug behind the back": "Encogimientos con barra por detrás",
  "bench press - with bands": "Press de banca con bandas",
  "bodyweight walking lunge": "Zancada caminando con peso corporal",
  "calf raise on a dumbbell": "Elevación de pantorrilla sobre mancuerna",
  "close-grip ez bar curl": "Curl con barra EZ agarre cerrado",
  "close-grip standing barbell curl": "Curl de pie agarre cerrado con barra",
  "concentration curls": "Curl de concentración",
  "cross body hammer curl": "Curl martillo cruzado",
  "crunches": "Abdominales",
  "decline crunch": "Crunch declinado",
  "decline dumbbell triceps extension": "Extensión de tríceps declinada con mancuernas",
  "decline push-up": "Flexión declinada",
  "dumbbell alternate bicep curl": "Curl de bíceps alterno con mancuernas",
  "dumbbell bicep curl": "Curl de bíceps con mancuernas",
  "dumbbell flyes": "Apertura con mancuernas",
  "dumbbell incline shoulder raise": "Elevación de hombros inclinada con mancuernas",
  "dumbbell lying one-arm rear lateral raise": "Elevación lateral posterior un brazo acostado",
  "dumbbell lying rear lateral raise": "Elevación lateral posterior acostado con mancuernas",
  "dumbbell one-arm triceps extension": "Extensión de tríceps un brazo con mancuerna",
  "dumbbell prone incline curl": "Curl en banco inclinado boca abajo con mancuernas",
  "dumbbell seated one-leg calf raise": "Elevación de pantorrilla una pierna sentado con mancuerna",
  "dumbbell shrug": "Encogimientos con mancuernas",
  "dumbbell tricep extension -pronated grip": "Extensión de tríceps agarre pronado con mancuerna",
  "flat bench lying leg raise": "Elevación de piernas acostado en banco plano",
  "front dumbbell raise": "Elevación frontal con mancuerna",
  "front incline dumbbell raise": "Elevación frontal inclinada con mancuernas",
  "hammer curls": "Curl martillo",
  "hanging leg raise": "Elevación de piernas en suspensión",
  "incline barbell triceps extension": "Extensión de tríceps inclinada con barra",
  "incline dumbbell curl": "Curl inclinado con mancuernas",
  "incline hammer curls": "Curl martillo inclinado",
  "incline inner biceps curl": "Curl interior de bíceps inclinado",
  "lying dumbbell tricep extension": "Extensión de tríceps acostado con mancuernas",
  "lying high bench barbell curl": "Curl con barra en banco alto acostado",
  "lying one-arm lateral raise": "Elevación lateral un brazo acostado",
  "lying rear delt raise": "Elevación posterior de deltoides acostado",
  "lying supine dumbbell curl": "Curl supino acostado con mancuernas",
  "oblique crunches": "Crunches oblicuos",
  "oblique crunches - on the floor": "Crunches oblicuos en el suelo",
  "one-arm incline lateral raise": "Elevación lateral inclinada un brazo",
  "one arm chin-up": "Dominada supina un brazo",
  "one arm dumbbell preacher curl": "Curl en predicador un brazo con mancuerna",
  "one arm pronated dumbbell triceps extension": "Extensión de tríceps pronada un brazo con mancuerna",
  "one arm supinated dumbbell triceps extension": "Extensión de tríceps supinada un brazo con mancuerna",
  "palms-down dumbbell wrist curl over a bench": "Curl de muñeca prono con mancuerna",
  "palms-up barbell wrist curl over a bench": "Curl de muñeca supino con barra",
  "parallel bar dip": "Fondos en barras paralelas",
  "plank": "Plancha",
  "preacher curl": "Curl en predicador",
  "preacher hammer dumbbell curl": "Curl martillo en predicador con mancuerna",
  "reverse barbell curl": "Curl inverso con barra",
  "reverse crunch": "Crunch inverso",
  "reverse flyes": "Vuelos inversos",
  "reverse flyes with external rotation": "Vuelos inversos con rotación externa",
  "ring dips": "Fondos en anillas",
  "seated bent-over rear delt raise": "Elevación posterior de deltoides sentado inclinado",
  "seated close-grip concentration barbell curl": "Curl de concentración agarre cerrado con barra",
  "seated dumbbell curl": "Curl sentado con mancuernas",
  "seated dumbbell inner biceps curl": "Curl interior de bíceps sentado con mancuernas",
  "seated dumbbell palms-down wrist curl": "Curl de muñeca prono sentado con mancuernas",
  "seated dumbbell palms-up wrist curl": "Curl de muñeca supino sentado con mancuernas",
  "seated one-arm dumbbell palms-down wrist curl": "Curl de muñeca prono un brazo sentado",
  "seated one-arm dumbbell palms-up wrist curl": "Curl de muñeca supino un brazo sentado",
  "seated palm-up barbell wrist curl": "Curl de muñeca supino sentado con barra",
  "seated palms-down barbell wrist curl": "Curl de muñeca prono sentado con barra",
  "seated side lateral raise": "Elevación lateral sentado",
  "shoulder press - with bands": "Press de hombros con bandas",
  "side lateral raise": "Elevación lateral",
  "side laterals to front raise": "Elevación lateral a elevación frontal",
  "single-leg high box squat": "Sentadilla una pierna en cajón alto",
  "single dumbbell raise": "Elevación simple con mancuerna",
  "single leg glute bridge": "Puente de glúteo una pierna",
  "sit-up": "Abdominal completo",
  "smith incline shoulder raise": "Elevación de hombros inclinada en máquina Smith",
  "squats - with bands": "Sentadillas con bandas",
  "standing barbell calf raise": "Elevación de pantorrilla de pie con barra",
  "standing dumbbell calf raise": "Elevación de pantorrilla de pie con mancuerna",
  "standing dumbbell reverse curl": "Curl inverso de pie con mancuernas",
  "standing dumbbell triceps extension": "Extensión de tríceps de pie con mancuerna",
  "standing front barbell raise over head": "Elevación frontal sobre cabeza con barra",
  "standing inner-biceps curl": "Curl interior de bíceps de pie",
  "standing one-arm dumbbell triceps extension": "Extensión de tríceps un brazo de pie con mancuerna",
  "standing overhead barbell triceps extension": "Extensión de tríceps sobre cabeza con barra",
  "standing towel triceps extension": "Extensión de tríceps con toalla de pie",
  "suspended push-up": "Flexión suspendida",
  "suspended split squat": "Sentadilla dividida suspendida",
  "trap bar deadlift": "Peso muerto con barra hexagonal",
  "tuck crunch": "Crunch encogido",
  "two-arm dumbbell preacher curl": "Curl en predicador dos brazos con mancuernas",
  "weighted bench dip": "Fondos en banco con peso",
  "weighted pull ups": "Dominadas con peso",
  "weighted squat": "Sentadilla con peso adicional",
  "wide-grip standing barbell curl": "Curl de pie agarre ancho con barra",
  "zottman curl": "Curl Zottman",
  "zottman preacher curl": "Curl Zottman en predicador",
  "air bike": "Bicicleta de aire",
  "arnold dumbbell press": "Press Arnold con mancuernas",
  "barbell ab rollout": "Rueda abdominal con barra",
  "barbell ab rollout - on knees": "Rueda abdominal con barra de rodillas",
  "barbell rear delt row": "Remo para deltoides posterior con barra",
  // stretching
  "90/90 hamstring": "Estiramiento de isquiotibiales 90/90",
  "adductor": "Estiramiento de aductores",
  "adductor/groin": "Estiramiento de aductores e ingle",
  "all fours quad stretch": "Estiramiento de cuádriceps en cuatro apoyos",
  "ankle circles": "Círculos de tobillo",
  "ankle on the knee": "Tobillo sobre la rodilla",
  "anterior tibialis-smr": "Liberación miofascial del tibial anterior",
  "arm circles": "Círculos de brazos",
  "behind head chest stretch": "Estiramiento de pecho detrás de la cabeza",
  "brachialis-smr": "Liberación miofascial del braquial",
  "calf stretch elbows against wall": "Estiramiento de pantorrilla con codos en pared",
  "calf stretch hands against wall": "Estiramiento de pantorrilla con manos en pared",
  "calves-smr": "Liberación miofascial de pantorrillas",
  "cat stretch": "Estiramiento del gato",
  "chair leg extended stretch": "Estiramiento de pierna extendida en silla",
  "chair lower back stretch": "Estiramiento de espalda baja en silla",
  "chair upper body stretch": "Estiramiento de tren superior en silla",
  "chest and front of shoulder stretch": "Estiramiento de pecho y deltoides anterior",
  "chest stretch on stability ball": "Estiramiento de pecho en pelota de estabilidad",
  "child's pose": "Postura del niño",
  "chin to chest stretch": "Estiramiento barbilla al pecho",
  "crossover reverse lunge": "Zancada inversa cruzada",
  "dancer's stretch": "Estiramiento del bailarín",
  "dynamic back stretch": "Estiramiento dinámico de espalda",
  "dynamic chest stretch": "Estiramiento dinámico de pecho",
  "elbow circles": "Círculos de codo",
  "elbows back": "Codos atrás",
  "foot-smr": "Liberación miofascial del pie",
  "front leg raises": "Elevaciones frontales de pierna",
  "groin and back stretch": "Estiramiento de ingle y espalda",
  "groiners": "Estiramiento dinámico de cadera",
  "hamstring-smr": "Liberación miofascial de isquiotibiales",
  "hamstring stretch": "Estiramiento de isquiotibiales",
  "hip circles (prone)": "Círculos de cadera boca abajo",
  "hug a ball": "Abrazar una pelota",
  "hug knees to chest": "Rodillas al pecho",
  "it band and glute stretch": "Estiramiento de cintilla iliotibial y glúteo",
  "iliotibial tract-smr": "Liberación miofascial de la cintilla iliotibial",
  "inchworm": "Gusano",
  "intermediate groin stretch": "Estiramiento de ingle intermedio",
  "intermediate hip flexor and quad stretch": "Estiramiento de flexores de cadera y cuádriceps",
  "iron crosses (stretch)": "Cruces de hierro",
  "knee across the body": "Rodilla al lado opuesto",
  "knee circles": "Círculos de rodilla",
  "kneeling forearm stretch": "Estiramiento de antebrazo de rodillas",
  "kneeling hip flexor": "Estiramiento de flexores de cadera de rodillas",
  "latissimus dorsi-smr": "Liberación miofascial del dorsal ancho",
  "leg-up hamstring stretch": "Estiramiento de isquiotibiales con pierna elevada",
  "looking at ceiling": "Mirar al techo",
  "lower back-smr": "Liberación miofascial de espalda baja",
  "lower back curl": "Curl de espalda baja",
  "lying bent leg groin": "Estiramiento de ingle acostado rodilla flexionada",
  "lying crossover": "Cruce acostado",
  "lying glute": "Estiramiento de glúteo acostado",
  "lying hamstring": "Estiramiento de isquiotibiales acostado",
  "lying prone quadriceps": "Estiramiento de cuádriceps boca abajo",
  "middle back stretch": "Estiramiento de espalda media",
  "neck-smr": "Liberación miofascial del cuello",
  "on-your-back quad stretch": "Estiramiento de cuádriceps boca arriba",
  "on your side quad stretch": "Estiramiento de cuádriceps de lado",
  "one arm against wall": "Un brazo contra la pared",
  "one half locust": "Media langosta",
  "one handed hang": "Colgada un brazo",
  "one knee to chest": "Una rodilla al pecho",
  "overhead lat": "Estiramiento del dorsal sobre cabeza",
  "overhead stretch": "Estiramiento sobre cabeza",
  "overhead triceps": "Estiramiento de tríceps sobre cabeza",
  "pelvic tilt into bridge": "Inclinación pélvica a puente",
  "peroneals-smr": "Liberación miofascial de peroneos",
  "peroneals stretch": "Estiramiento de peroneos",
  "piriformis-smr": "Liberación miofascial del piriforme",
  "posterior tibialis stretch": "Estiramiento del tibial posterior",
  "pyramid": "Pirámide",
  "quad stretch": "Estiramiento de cuádriceps",
  "quadriceps-smr": "Liberación miofascial de cuádriceps",
  "rear leg raises": "Elevaciones traseras de pierna",
  "rhomboids-smr": "Liberación miofascial de romboides",
  "round the world shoulder stretch": "Estiramiento circular de hombros",
  "runner's stretch": "Estiramiento del corredor",
  "scissor kick": "Patada tijera",
  "seated biceps": "Estiramiento de bíceps sentado",
  "seated calf stretch": "Estiramiento de pantorrilla sentado",
  "seated floor hamstring stretch": "Estiramiento de isquiotibiales en suelo sentado",
  "seated front deltoid": "Estiramiento del deltoides anterior sentado",
  "seated glute": "Estiramiento de glúteo sentado",
  "seated hamstring": "Estiramiento de isquiotibiales sentado",
  "seated hamstring and calf stretch": "Estiramiento de isquiotibiales y pantorrilla sentado",
  "seated overhead stretch": "Estiramiento sobre cabeza sentado",
  "shoulder circles": "Círculos de hombros",
  "shoulder raise": "Elevación de hombros",
  "shoulder stretch": "Estiramiento de hombros",
  "side-lying floor stretch": "Estiramiento lateral acostado en el suelo",
  "side leg raises": "Elevaciones laterales de pierna",
  "side lying groin stretch": "Estiramiento de ingle lateral acostado",
  "side neck stretch": "Estiramiento lateral del cuello",
  "side wrist pull": "Tirón lateral de muñeca",
  "sit squats": "Sentadilla-sentarse",
  "spinal stretch": "Estiramiento de columna",
  "split squats": "Sentadilla dividida",
  "standing biceps stretch": "Estiramiento de bíceps de pie",
  "standing elevated quad stretch": "Estiramiento elevado de cuádriceps de pie",
  "standing gastrocnemius calf stretch": "Estiramiento de gemelo de pie",
  "standing hamstring and calf stretch": "Estiramiento de isquiotibiales y pantorrilla de pie",
  "standing hip circles": "Círculos de cadera de pie",
  "standing hip flexors": "Estiramiento de flexores de cadera de pie",
  "standing lateral stretch": "Estiramiento lateral de pie",
  "standing pelvic tilt": "Inclinación pélvica de pie",
  "standing soleus and achilles stretch": "Estiramiento de sóleo y talón de Aquiles de pie",
  "standing toe touches": "Toque de pies de pie",
  "stomach vacuum": "Vacío abdominal",
  "superman": "Superman",
  "the straddle": "Apertura de piernas",
  "toe touchers": "Toque de dedos del pie",
  "torso rotation": "Rotación de torso",
  "tricep side stretch": "Estiramiento lateral de tríceps",
  "triceps stretch": "Estiramiento de tríceps",
  "upper back-leg grab": "Agarre espalda alta-pierna",
  "upper back stretch": "Estiramiento de espalda alta",
  "upward stretch": "Estiramiento hacia arriba",
  "windmills": "Molinos de viento",
  "world's greatest stretch": "El mejor estiramiento del mundo",
  "wrist circles": "Círculos de muñeca",
  // plyometrics
  "alternate leg diagonal bound": "Salto diagonal alterno",
  "backward medicine ball throw": "Lanzamiento hacia atrás con balón medicinal",
  "bench jump": "Salto al banco",
  "bench sprint": "Sprint en banco",
  "box jump (multiple response)": "Salto al cajón (múltiple)",
  "box skip": "Salto en cajón",
  "carioca quick step": "Paso carioca rápido",
  "catch and overhead throw": "Atrapar y lanzar sobre cabeza",
  "chest push from 3 point stance": "Empuje de pecho desde 3 apoyos",
  "chest push (multiple response)": "Empuje de pecho (múltiple)",
  "chest push (single response)": "Empuje de pecho (simple)",
  "chest push with run release": "Empuje de pecho con salida",
  "depth jump leap": "Salto en profundidad",
  "double leg butt kick": "Talón al glúteo dos piernas",
  "drop push": "Empuje en caída",
  "dumbbell seated box jump": "Salto al cajón sentado con mancuernas",
  "fast skipping": "Salto con cuerda rápido",
  "front box jump": "Salto frontal al cajón",
  "front cone hops (or hurdle hops)": "Saltos frontales con conos",
  "frog hops": "Saltos de rana",
  "heavy bag thrust": "Empuje de saco pesado",
  "hurdle hops": "Saltos de valla",
  "incline push-up depth jump": "Salto en profundidad en flexión inclinada",
  "isometric chest squeezes": "Apretones isométricos de pecho",
  "knee tuck jump": "Salto con rodillas al pecho",
  "kneeling arm drill": "Ejercicio de brazos de rodillas",
  "lateral bound": "Salto lateral",
  "lateral box jump": "Salto lateral al cajón",
  "lateral cone hops": "Saltos laterales con conos",
  "linear 3-part start technique": "Técnica de inicio lineal en 3 partes",
  "linear acceleration wall drill": "Ejercicio de aceleración lineal en pared",
  "linear depth jump": "Salto lineal en profundidad",
  "medicine ball chest pass": "Pase de pecho con balón medicinal",
  "medicine ball full twist": "Giro completo con balón medicinal",
  "medicine ball scoop throw": "Lanzamiento cuchara con balón medicinal",
  "mountain climbers": "Escaladores de montaña",
  "moving claw series": "Serie de garras en movimiento",
  "overhead slam": "Golpe sobre cabeza",
  "plyo push-up": "Flexión pliométrica",
  "quick leap": "Salto rápido",
  "return push from stance": "Empuje de retorno desde posición",
  "rocket jump": "Salto cohete",
  "scissors jump": "Salto de tijeras",
  "side hop-sprint": "Salto lateral con sprint",
  "side standing long jump": "Salto largo lateral de pie",
  "side to side box shuffle": "Desplazamiento lateral en cajón",
  "single-cone sprint drill": "Ejercicio de sprint en cono",
  "single-leg hop progression": "Progresión de saltos una pierna",
  "single-leg lateral hop": "Salto lateral una pierna",
  "single-leg stride jump": "Salto de zancada una pierna",
  "single leg butt kick": "Talón al glúteo una pierna",
  "single leg push-off": "Despegue una pierna",
  "sledgehammer swings": "Golpes con mazo",
  "split jump": "Salto dividido",
  "star jump": "Salto estrella",
  "standing long jump": "Salto largo de pie",
  "standing two-arm overhead throw": "Lanzamiento sobre cabeza dos brazos de pie",
  "stride jump crossover": "Salto de zancada cruzado",
  "supine chest throw": "Lanzamiento de pecho supino",
  "supine one-arm overhead throw": "Lanzamiento sobre cabeza un brazo supino",
  "supine two-arm overhead throw": "Lanzamiento sobre cabeza dos brazos supino",
  "vertical swing": "Swing vertical",
  // strongman
  "atlas stone trainer": "Entrenador de piedra Atlas",
  "atlas stones": "Piedras Atlas",
  "axle deadlift": "Peso muerto con eje",
  "backward drag": "Arrastre hacia atrás",
  "bear crawl sled drags": "Arrastre en cuatro patas con trineo",
  "car deadlift": "Peso muerto de auto",
  "circus bell": "Campana de circo",
  "conan's wheel": "Rueda de Conan",
  "crucifix": "Crucifijo",
  "farmer's walk": "Caminata del granjero",
  "forward drag with press": "Arrastre frontal con empuje",
  "keg load": "Carga de barril",
  "log lift": "Levantamiento de tronco",
  "power stairs": "Escalones de potencia",
  "rickshaw carry": "Cargada con rickshaw",
  "rickshaw deadlift": "Peso muerto con rickshaw",
  "sandbag load": "Carga de saco de arena",
  "sled drag - harness": "Arrastre de trineo con arnés",
  "sled push": "Empuje de trineo",
  "tire flip": "Volteo de llanta",
  "yoke walk": "Caminata con yugo",
  // powerlifting
  "band good morning": "Buenos días con banda",
  "band good morning (pull through)": "Buenos días con banda (tire a través)",
  "barbell glute bridge": "Puente de glúteo con barra",
  "barbell hip thrust": "Hip thrust con barra",
  "bench press - powerlifting": "Press de banca - Powerlifting",
  "bench press with chains": "Press de banca con cadenas",
  "board press": "Press con tabla",
  "box squat": "Sentadilla en cajón",
  "box squat with bands": "Sentadilla en cajón con bandas",
  "chain handle extension": "Extensión con mango de cadena",
  "chain press": "Press con cadenas",
  "deadlift with bands": "Peso muerto con bandas",
  "deadlift with chains": "Peso muerto con cadenas",
  "deficit deadlift": "Peso muerto en déficit",
  "dumbbell floor press": "Press de suelo con mancuernas",
  "floor press": "Press de suelo",
  "floor press with chains": "Press de suelo con cadenas",
  "glute ham raise": "Curl femoral invertido",
  "good morning": "Buenos días",
  "good morning off pins": "Buenos días desde pines",
  "hanging bar good morning": "Buenos días colgado en barra",
  "hip lift with band": "Elevación de cadera con banda",
  "kneeling squat": "Sentadilla de rodillas",
  "pin presses": "Press desde pines",
  "rack pull with bands": "Jalón desde rack con bandas",
  "rack pulls": "Jalones desde rack",
  "reverse band bench press": "Press de banca con banda invertida",
  "reverse band box squat": "Sentadilla en cajón con banda invertida",
  "reverse band deadlift": "Peso muerto con banda invertida",
  "reverse band power squat": "Sentadilla de potencia con banda invertida",
  "reverse band sumo deadlift": "Sumo deadlift con banda invertida",
  "seated good mornings": "Buenos días sentado",
  "speed box squat": "Sentadilla en cajón explosiva",
  "squat with bands": "Sentadilla con bandas",
  "squat with chains": "Sentadilla con cadenas",
  "sumo deadlift": "Peso muerto sumo",
  "sumo deadlift with bands": "Peso muerto sumo con bandas",
  "sumo deadlift with chains": "Peso muerto sumo con cadenas",
  // olympic weightlifting
  "clean": "Clean",
  "clean deadlift": "Peso muerto de clean",
  "clean pull": "Tirón de clean",
  "clean shrug": "Encogimiento de clean",
  "clean and jerk": "Clean y Jerk",
  "clean from blocks": "Clean desde bloques",
  "frankenstein squat": "Sentadilla Frankenstein",
  "hang clean": "Hang clean",
  "hang clean - below the knees": "Hang clean debajo de las rodillas",
  "hang snatch": "Hang snatch",
  "hang snatch - below knees": "Hang snatch debajo de las rodillas",
  "heaving snatch balance": "Balance de snatch con impulso",
  "jerk balance": "Balance del jerk",
  "jerk dip squat": "Sentadilla de impulso del jerk",
  "kneeling jump squat": "Sentadilla con salto de rodillas",
  "muscle snatch": "Muscle snatch",
  "olympic squat": "Sentadilla olímpica",
  "overhead squat": "Sentadilla sobre cabeza",
  "power clean from blocks": "Power clean desde bloques",
  "power jerk": "Power jerk",
  "power snatch": "Power snatch",
  "power snatch from blocks": "Power snatch desde bloques",
  "push press": "Push press",
  "push press - behind the neck": "Push press por detrás del cuello",
  "rack delivery": "Entrega en rack",
  "romanian deadlift from deficit": "Peso muerto rumano desde déficit",
  "snatch": "Snatch",
  "snatch balance": "Balance de snatch",
  "snatch deadlift": "Peso muerto de snatch",
  "snatch shrug": "Encogimiento de snatch",
  "snatch from blocks": "Snatch desde bloques",
  "split clean": "Clean dividido",
  "split jerk": "Jerk dividido",
  "split snatch": "Snatch dividido",
  "wide stance stiff legs": "Piernas rígidas postura ancha",
  // cardio
  "bicycling": "Ciclismo",
  "bicycling, stationary": "Bicicleta estática",
  "elliptical trainer": "Máquina elíptica",
  "jogging, treadmill": "Trote en cinta",
  "prowler sprint": "Sprint con trineo Prowler",
  "recumbent bike": "Bicicleta reclinada",
  "rope jumping": "Salto con cuerda",
  "rowing, stationary": "Remo estático",
  "running, treadmill": "Carrera en cinta",
  "skating": "Patinaje",
  "stairmaster": "Escaladora",
  "step mill": "Escaladora de peldaños",
  "trail running/walking": "Carrera y caminata en trail",
  "walking, treadmill": "Caminata en cinta",
};

// ── Traductor de instrucciones ─────────────────────────────────────────────────

/**
 * Ordered array of [regex, replacement] pairs.
 * Applied in order: longest/most-specific phrases first, then words.
 */
const INSTRUCTION_RULES = [
  // ── Phase 1: Full phrases ────────────────────────────────────────────────────
  [/this will be your starting position/gi, "esta es tu posición inicial"],
  [/this is your starting position/gi, "esta es tu posición inicial"],
  [/return to the starting position/gi, "regresa a la posición inicial"],
  [/back to the starting position/gi, "de vuelta a la posición inicial"],
  [/back to starting position/gi, "de vuelta a la posición inicial"],
  [/starting position/gi, "posición inicial"],
  [/full range of motion/gi, "rango completo de movimiento"],
  [/range of motion/gi, "rango de movimiento"],
  [/as you breathe out/gi, "mientras exhalas"],
  [/as you breathe in/gi, "mientras inhalas"],
  [/breathe out/gi, "exhala"],
  [/breathe in/gi, "inhala"],
  [/at the top of the movement/gi, "en el punto más alto del movimiento"],
  [/at the top/gi, "en el punto más alto"],
  [/at the bottom of the movement/gi, "en el punto más bajo del movimiento"],
  [/at the bottom/gi, "en el punto más bajo"],
  [/palms facing forward/gi, "palmas hacia adelante"],
  [/palms facing up/gi, "palmas hacia arriba"],
  [/palms facing down/gi, "palmas hacia abajo"],
  [/palms facing each other/gi, "palmas enfrentadas"],
  [/palms facing/gi, "palmas hacia"],
  [/overhand grip/gi, "agarre en pronación"],
  [/underhand grip/gi, "agarre en supinación"],
  [/pronated grip/gi, "agarre en pronación"],
  [/supinated grip/gi, "agarre en supinación"],
  [/neutral grip/gi, "agarre neutro"],
  [/recommended amount of repetitions/gi, "número de repeticiones recomendadas"],
  [/desired number of repetitions/gi, "número de repeticiones deseadas"],
  [/upper and lower/gi, "superior e inferior"],
  [/90-degree angle/gi, "ángulo de 90 grados"],
  [/90 degree angle/gi, "ángulo de 90 grados"],
  [/for the recommended/gi, "durante las repeticiones recomendadas"],
  [/upper arms/gi, "la parte superior de los brazos"],
  [/lower back/gi, "la espalda baja"],
  [/upper back/gi, "la espalda alta"],
  [/middle back/gi, "la espalda media"],
  [/hip flexors/gi, "flexores de cadera"],
  [/hip-width apart/gi, "al ancho de la cadera"],
  [/hip width apart/gi, "al ancho de la cadera"],
  [/hip-width/gi, "al ancho de la cadera"],
  [/hip width/gi, "al ancho de la cadera"],
  [/shoulder-width apart/gi, "al ancho de hombros"],
  [/shoulder width apart/gi, "al ancho de hombros"],
  [/shoulder-width/gi, "al ancho de hombros"],
  [/shoulder width/gi, "al ancho de hombros"],
  [/feet flat on the floor/gi, "pies planos en el suelo"],
  [/balls of your feet/gi, "la parte delantera de tus pies"],
  [/balls of the feet/gi, "la parte delantera de los pies"],
  [/hold the contraction/gi, "mantén la contracción"],
  [/contracted position/gi, "posición contraída"],
  [/repeat for/gi, "repite durante"],
  [/repeat on the other side/gi, "repite en el otro lado"],
  [/repeat on the other/gi, "repite en el otro"],
  [/switch sides/gi, "cambia de lado"],
  [/switch legs/gi, "cambia de pierna"],
  [/the other leg/gi, "la otra pierna"],
  [/the other arm/gi, "el otro brazo"],
  [/lower the weight/gi, "baja el peso"],
  [/raise the weight/gi, "sube el peso"],
  [/in a controlled manner/gi, "de forma controlada"],
  [/under control/gi, "de forma controlada"],
  [/slightly bent/gi, "ligeramente flexionados"],
  [/slightly bowed/gi, "ligeramente arqueados"],
  [/keep your back straight/gi, "mantén la espalda recta"],
  [/keep your back flat/gi, "mantén la espalda plana"],
  [/flat on the bench/gi, "plano en el banco"],
  [/lie on your back/gi, "acuéstate boca arriba"],
  [/lie on your stomach/gi, "acuéstate boca abajo"],
  [/lie face down/gi, "acuéstate boca abajo"],
  [/lie face up/gi, "acuéstate boca arriba"],
  [/lie on a/gi, "acuéstate en"],
  [/lie on the/gi, "acuéstate en"],
  [/stand up straight/gi, "párate erguido"],
  [/stand with your feet/gi, "párate con los pies"],
  [/stand with your/gi, "párate con"],
  [/stand with feet/gi, "párate con los pies"],
  [/grab the bar/gi, "agarra la barra"],
  [/grip the bar/gi, "agarra la barra"],
  [/get into position/gi, "colócate en posición"],
  [/get into/gi, "colócate en"],
  [/sit on a/gi, "siéntate en"],
  [/sit on the/gi, "siéntate en"],
  [/make sure/gi, "asegúrate de"],
  [/keeping your/gi, "manteniendo"],
  [/keeping the/gi, "manteniendo"],
  [/hold this position/gi, "mantén esta posición"],
  [/hold for/gi, "mantén durante"],
  [/feel a stretch/gi, "siente el estiramiento"],
  [/feel the stretch/gi, "siente el estiramiento"],
  [/until you feel/gi, "hasta que sientas"],
  [/as far as possible/gi, "lo más lejos posible"],
  [/as far as you can/gi, "todo lo que puedas"],
  [/as high as possible/gi, "lo más alto posible"],
  [/as low as possible/gi, "lo más bajo posible"],
  [/in front of you/gi, "frente a ti"],
  [/in front of your/gi, "frente a tus"],
  [/behind your/gi, "detrás de tus"],
  [/behind you/gi, "detrás de ti"],
  [/above your/gi, "sobre tus"],
  [/above you/gi, "sobre ti"],
  [/next to your/gi, "junto a tus"],
  [/to your side/gi, "a tu lado"],
  [/at your sides/gi, "a tus costados"],
  [/at your side/gi, "a tu costado"],
  [/on each side/gi, "de cada lado"],
  [/on both sides/gi, "en ambos lados"],
  [/each repetition/gi, "cada repetición"],
  [/each set/gi, "cada serie"],
  [/the floor/gi, "el suelo"],
  [/the ground/gi, "el suelo"],
  [/the ceiling/gi, "el techo"],
  [/the wall/gi, "la pared"],
  [/a slight bend/gi, "una ligera flexión"],
  [/a slight arch/gi, "una ligera curvatura"],
  [/your chest/gi, "tu pecho"],
  [/your back/gi, "tu espalda"],
  [/your core/gi, "tu core"],
  [/your body/gi, "tu cuerpo"],
  [/your head/gi, "tu cabeza"],
  [/your neck/gi, "tu cuello"],
  [/your spine/gi, "tu columna"],
  [/your legs/gi, "tus piernas"],
  [/your arms/gi, "tus brazos"],
  [/your hands/gi, "tus manos"],
  [/your feet/gi, "tus pies"],
  [/your toes/gi, "tus dedos del pie"],
  [/your heels/gi, "tus talones"],
  [/your shoulders/gi, "tus hombros"],
  [/your elbows/gi, "tus codos"],
  [/your knees/gi, "tus rodillas"],
  [/your hips/gi, "tus caderas"],
  [/your glutes/gi, "tus glúteos"],
  [/your wrists/gi, "tus muñecas"],
  [/your ankles/gi, "tus tobillos"],
  [/your lats/gi, "tus dorsales"],
  [/your abs/gi, "tus abdominales"],
  [/your hamstrings/gi, "tus isquiotibiales"],
  [/your quads/gi, "tus cuádriceps"],
  [/your calves/gi, "tus pantorrillas"],
  [/your forearms/gi, "tus antebrazos"],
  [/your traps/gi, "tus trapecios"],
  [/your delts/gi, "tus deltoides"],
  [/your biceps/gi, "tus bíceps"],
  [/your triceps/gi, "tus tríceps"],

  // ── Phase 2: Body parts (standalone) ────────────────────────────────────────
  [/\bshoulders\b/gi, "hombros"],
  [/\bshoulder\b/gi, "hombro"],
  [/\belbows\b/gi, "codos"],
  [/\belbow\b/gi, "codo"],
  [/\bknees\b/gi, "rodillas"],
  [/\bknee\b/gi, "rodilla"],
  [/\bwrists\b/gi, "muñecas"],
  [/\bwrist\b/gi, "muñeca"],
  [/\bhips\b/gi, "caderas"],
  [/\bhip\b/gi, "cadera"],
  [/\bankles\b/gi, "tobillos"],
  [/\bankle\b/gi, "tobillo"],
  [/\bforearms\b/gi, "antebrazos"],
  [/\bforearm\b/gi, "antebrazo"],
  [/\btriceps\b/gi, "tríceps"],
  [/\bbiceps\b/gi, "bíceps"],
  [/\bglutes\b/gi, "glúteos"],
  [/\bglute\b/gi, "glúteo"],
  [/\bhamstrings\b/gi, "isquiotibiales"],
  [/\bhamstring\b/gi, "isquiotibial"],
  [/\bquadriceps\b/gi, "cuádriceps"],
  [/\bquads\b/gi, "cuádriceps"],
  [/\bcalves\b/gi, "pantorrillas"],
  [/\bcalf\b/gi, "pantorrilla"],
  [/\bchest\b/gi, "pecho"],
  [/\bspine\b/gi, "columna vertebral"],
  [/\btraps\b/gi, "trapecios"],
  [/\btrap\b/gi, "trapecio"],
  [/\bdelts\b/gi, "deltoides"],
  [/\bdelt\b/gi, "deltoides"],
  [/\blats\b/gi, "dorsales"],
  [/\blat\b/gi, "dorsal"],
  [/\bcore\b/gi, "core"],
  [/\btorso\b/gi, "torso"],
  [/\bneck\b/gi, "cuello"],
  [/\bshins\b/gi, "espinillas"],
  [/\bshin\b/gi, "espinilla"],
  [/\bthighs\b/gi, "muslos"],
  [/\bthigh\b/gi, "muslo"],
  [/\bwrists\b/gi, "muñecas"],

  // ── Phase 3: Equipment ───────────────────────────────────────────────────────
  [/\bbarbells\b/gi, "barras"],
  [/\bbarbell\b/gi, "barra"],
  [/\bdumbbells\b/gi, "mancuernas"],
  [/\bdumbbell\b/gi, "mancuerna"],
  [/\bcable machine\b/gi, "máquina de cable"],
  [/\bbench\b/gi, "banco"],
  [/\bplatform\b/gi, "plataforma"],
  [/\bbands\b/gi, "bandas"],
  [/\bband\b/gi, "banda"],
  [/\bchains\b/gi, "cadenas"],
  [/\bchain\b/gi, "cadena"],
  [/\bkettlebell\b/gi, "pesa rusa"],
  [/\bpulldown machine\b/gi, "máquina de jalón"],
  [/\bcable\b/gi, "cable"],

  // ── Phase 4: Action verbs (imperative) ──────────────────────────────────────
  [/\bpause\b/gi, "haz una pausa"],
  [/\bsqueeze\b/gi, "aprieta"],
  [/\bcontract\b/gi, "contrae"],
  [/\bexhale\b/gi, "exhala"],
  [/\binhale\b/gi, "inhala"],
  [/\bgrasp\b/gi, "agarra"],
  [/\bplace\b/gi, "coloca"],
  [/\badjust\b/gi, "ajusta"],
  [/\bextend\b/gi, "extiende"],
  [/\blower\b/gi, "baja"],
  [/\braise\b/gi, "eleva"],
  [/\bpush\b/gi, "empuja"],
  [/\bpull\b/gi, "jala"],
  [/\bpress\b/gi, "presiona"],
  [/\bkick\b/gi, "patea"],
  [/\bjump\b/gi, "salta"],
  [/\bland\b/gi, "aterriza"],
  [/\brepeat\b/gi, "repite"],
  [/\bperform\b/gi, "realiza"],
  [/\bexecute\b/gi, "ejecuta"],
  [/\bbegin\b/gi, "comienza"],
  [/\bfinish\b/gi, "termina"],
  [/\bcomplete\b/gi, "completa"],
  [/\btighten\b/gi, "aprieta"],
  [/\brelax\b/gi, "relaja"],
  [/\bwalk\b/gi, "camina"],
  [/\bswing\b/gi, "balancea"],
  [/\brotate\b/gi, "rota"],
  [/\btwist\b/gi, "gira"],
  [/\btilt\b/gi, "inclina"],
  [/\barch\b/gi, "arquea"],
  [/\bflex\b/gi, "flexiona"],
  [/\bbend\b/gi, "flexiona"],
  [/\bgrip\b/gi, "agarra"],
  [/\bhold\b/gi, "mantén"],
  [/\bstart\b/gi, "comienza"],
  [/\breturn\b/gi, "regresa"],
  [/\bstep\b/gi, "da un paso"],
  [/\blift\b/gi, "levanta"],
  [/\bdrop\b/gi, "baja"],
  [/\bbring\b/gi, "lleva"],
  [/\bkeep\b/gi, "mantén"],
  [/\bengage\b/gi, "activa"],
  [/\bactivate\b/gi, "activa"],
  [/\binhale\b/gi, "inhala"],
  [/\bexhale\b/gi, "exhala"],
  [/\bsit\b/gi, "siéntate"],
  [/\bstand\b/gi, "párate"],
  [/\bwrap\b/gi, "envuelve"],
  [/\bpivot\b/gi, "gira"],
  [/\bleap\b/gi, "salta"],
  [/\bthrow\b/gi, "lanza"],
  [/\bcatch\b/gi, "atrapa"],
  [/\bpick\b/gi, "agarra"],
  [/\bposition\b/gi, "posiciona"],
  [/\bensure\b/gi, "asegúrate de que"],
  [/\binhale\b/gi, "inhala"],

  // ── Phase 5: Adjectives / Adverbs ────────────────────────────────────────────
  [/\bslowly\b/gi, "lentamente"],
  [/\bquickly\b/gi, "rápidamente"],
  [/\bgradually\b/gi, "gradualmente"],
  [/\bfully\b/gi, "completamente"],
  [/\bproperly\b/gi, "correctamente"],
  [/\bstraight\b/gi, "recto"],
  [/\bneutral\b/gi, "neutro"],
  [/\bparallel\b/gi, "paralelo"],
  [/\bperpendicular\b/gi, "perpendicular"],
  [/\bvertical\b/gi, "vertical"],
  [/\bhorizontal\b/gi, "horizontal"],
  [/\btight\b/gi, "firme"],
  [/\bwide\b/gi, "amplio"],
  [/\bheavy\b/gi, "pesado"],
  [/\blight\b/gi, "ligero"],
  [/\bcomfortable\b/gi, "cómodo"],
  [/\bcontrolled\b/gi, "controlado"],
  [/\bsteady\b/gi, "estable"],
  [/\bfirm\b/gi, "firme"],
  [/\bflat\b/gi, "plano"],
  [/\btall\b/gi, "erguido"],
  [/\bstrong\b/gi, "fuerte"],
  [/\btight\b/gi, "firme"],
  [/\bslow\b/gi, "lento"],
  [/\bfast\b/gi, "rápido"],
  [/\bquick\b/gi, "rápido"],
  [/\bexplosive\b/gi, "explosivo"],
  [/\bmaximum\b/gi, "máximo"],
  [/\bminimum\b/gi, "mínimo"],
  [/\boptimal\b/gi, "óptimo"],

  // ── Phase 6: Common connectors / prepositions ────────────────────────────────
  [/\bwithout\b/gi, "sin"],
  [/\buntil\b/gi, "hasta"],
  [/\bwhile\b/gi, "mientras"],
  [/\bduring\b/gi, "durante"],
  [/\bbefore\b/gi, "antes"],
  [/\bafter\b/gi, "después"],
  [/\bthen\b/gi, "luego"],
  [/\balternating\b/gi, "alternando"],
  [/\balternate\b/gi, "alterna"],
  [/\bsimultaneously\b/gi, "simultáneamente"],
  [/\bapproximately\b/gi, "aproximadamente"],
  [/\btip:/gi, "Consejo:"],
  [/\bnote:/gi, "Nota:"],
  [/\bwarning:/gi, "Advertencia:"],
  [/\bimportant:/gi, "Importante:"],
  [/\bfor example/gi, "por ejemplo"],
  [/\bsuch as/gi, "como por ejemplo"],
  [/\bin order to/gi, "para"],
  [/\bdue to\b/gi, "debido a"],
  [/\bregardless/gi, "independientemente"],

  // ── Phase 7: Positional words ────────────────────────────────────────────────
  [/\boverhead\b/gi, "sobre la cabeza"],
  [/\bupward\b/gi, "hacia arriba"],
  [/\bdownward\b/gi, "hacia abajo"],
  [/\bforward\b/gi, "hacia adelante"],
  [/\bbackward\b/gi, "hacia atrás"],
  [/\binward\b/gi, "hacia adentro"],
  [/\boutward\b/gi, "hacia afuera"],
  [/\blateral\b/gi, "lateral"],
  [/\bvertically\b/gi, "verticalmente"],
  [/\bhorizontally\b/gi, "horizontalmente"],
];

/**
 * Translate an array of instruction strings to Spanish using regex rules.
 */
function translateInstructions(steps) {
  if (!Array.isArray(steps)) return steps;
  return steps.map((step) => {
    if (typeof step !== "string") return step;
    let s = step;
    for (const [pattern, replacement] of INSTRUCTION_RULES) {
      s = s.replace(pattern, replacement);
    }
    return s;
  });
}

// ── Helpers ────────────────────────────────────────────────────────────────────

function translateArr(arr, map) {
  return (arr ?? []).map((v) => map[v?.toLowerCase()] ?? v);
}

// ── Main ───────────────────────────────────────────────────────────────────────

function main() {
  const exercises = JSON.parse(readFileSync(JSON_PATH, "utf-8"));
  console.log(`Loaded ${exercises.length} exercises.`);

  const translated = exercises.map((ex) => {
    const nameKey = ex.name?.toLowerCase?.() ?? "";
    const nameEs = NAME_ES[nameKey] ?? ex.name;

    return {
      id: ex.id,
      name: nameEs,
      level: LEVEL_ES[ex.level] ?? ex.level,
      mechanic: ex.mechanic !== null ? (MECHANIC_ES[ex.mechanic] ?? ex.mechanic) : null,
      category: CATEGORY_ES[ex.category] ?? ex.category,
      equipment: EQUIPMENT_ES[ex.equipment] ?? ex.equipment,
      targetedMuscles: translateArr(ex.targetedMuscles, MUSCLE_ES),
      bodyParts: translateArr(ex.bodyParts, BODY_PART_ES),
      secondaryMuscles: translateArr(ex.secondaryMuscles, MUSCLE_ES),
      instructions: translateInstructions(ex.instructions),
      gif: ex.gif ?? null,
    };
  });

  writeFileSync(JSON_PATH, JSON.stringify(translated, null, 2), "utf-8");

  // ── Stats ──────────────────────────────────────────────────────────────────
  const namesTranslated = translated.filter(
    (e, i) => e.name !== exercises[i].name
  ).length;
  const namesUntranslated = translated.filter(
    (e, i) => e.name === exercises[i].name
  );

  console.log(`\n✓ ${translated.length} exercises written to exercises-data.json`);
  console.log(`  Names translated:   ${namesTranslated}/${translated.length}`);
  if (namesUntranslated.length > 0) {
    console.log(
      `  Names kept in EN:   ${namesUntranslated.length} → ${namesUntranslated
        .map((e) => `"${e.name}"`)
        .slice(0, 5)
        .join(", ")}${namesUntranslated.length > 5 ? "..." : ""}`
    );
  }

  console.log("\n--- Sample (first exercise) ---");
  console.log(JSON.stringify(translated[0], null, 2));
}

main();
